import {
  Users,
  UserCheck,
  UsersRound,
  UserStar,
  UserCog,
  PersonStanding,
  HardHat,
  Briefcase,
  BriefcaseBusiness,
  Truck,
  TruckElectric,
  Car,
  Bus,
  Bike,
  Fuel,
  Package,
  ShieldCheck,
  Award,
  Trophy,
  Medal,
  Star,
  CircleStar,
  BadgeCheck,
  Crown,
  Sparkles,
  Zap,
  Bolt,
  Flame,
  Target,
  Goal,
  ThumbsUp,
  Handshake,
  HeartHandshake,
  HandHelping,
  TrendingUp,
  Activity,
  CircleGauge,
  Timer,
  Route,
  Navigation,
  Navigation2,
  Waypoints,
  TrafficCone,
  Rocket,
  Wrench,
  MapPin,
  MapPinCheck,
  MapPinHouse,
  MapPinned,
  LocateFixed,
  Compass,
  Milestone,
  Signpost,
  Globe,
  Plane,
  Ship,
  Building,
  Building2,
  Landmark,
  Warehouse,
  Factory,
  Home,
  Flag,
  Mountain,
  type LucideIcon,
} from "lucide-react";

export const BADGE_ICON_MAP: Record<string, LucideIcon> = {
  users: Users,
  "user-check": UserCheck,
  "users-round": UsersRound,
  "user-star": UserStar,
  "user-cog": UserCog,
  "person-standing": PersonStanding,
  "hard-hat": HardHat,
  briefcase: Briefcase,
  "briefcase-biz": BriefcaseBusiness,
  truck: Truck,
  "truck-electric": TruckElectric,
  car: Car,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  package: Package,
  "shield-check": ShieldCheck,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  star: Star,
  "circle-star": CircleStar,
  "badge-check": BadgeCheck,
  crown: Crown,
  sparkles: Sparkles,
  zap: Zap,
  bolt: Bolt,
  flame: Flame,
  target: Target,
  goal: Goal,
  "thumbs-up": ThumbsUp,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "hand-helping": HandHelping,
  "trending-up": TrendingUp,
  activity: Activity,
  "circle-gauge": CircleGauge,
  timer: Timer,
  route: Route,
  navigation: Navigation,
  "navigation-2": Navigation2,
  waypoints: Waypoints,
  "traffic-cone": TrafficCone,
  rocket: Rocket,
  wrench: Wrench,
  "map-pin": MapPin,
  "map-pin-check": MapPinCheck,
  "map-pin-house": MapPinHouse,
  "map-pinned": MapPinned,
  "locate-fixed": LocateFixed,
  compass: Compass,
  milestone: Milestone,
  signpost: Signpost,
  globe: Globe,
  plane: Plane,
  ship: Ship,
  building: Building,
  "building-2": Building2,
  landmark: Landmark,
  warehouse: Warehouse,
  factory: Factory,
  home: Home,
  flag: Flag,
  mountain: Mountain,
};
