import {
  Phone,
  Mail,
  MapPin,
  Smartphone,
  MessageCircle,
  AtSign,
  Inbox,
  MailOpen,
  Navigation,
  Globe,
  Building,
  Home,
  Handshake,
  HeartHandshake,
  Compass,
  type LucideIcon,
} from "lucide-react";

export const CONTACT_ROW_ICON_MAP: Record<string, LucideIcon> = {
  phone: Phone,
  smartphone: Smartphone,
  "message-circle": MessageCircle,
  mail: Mail,
  "at-sign": AtSign,
  inbox: Inbox,
  "mail-open": MailOpen,
  "map-pin": MapPin,
  navigation: Navigation,
  globe: Globe,
  building: Building,
  home: Home,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  compass: Compass,
};
