import {
  Home,
  Wifi,
  Utensils,
  MapPin,
  Phone,
  BedDouble,
  Coffee,
  Bath,
  DoorOpen,
  Armchair,
  Sofa,
  Sun,
  Key,
  Lamp,
  Lightbulb,
  Refrigerator,
  WashingMachine,
  CookingPot,
  Wind,
  Tv,
  Bed,
  Warehouse,
  Building,
  Building2,
  Truck,
  Car,
  Bus,
  Bike,
  Route,
  Shield,
  ShieldCheck,
  Star,
  Award,
  Sparkles,
  Heart,
  Users,
  CheckCircle2,
  type LucideIcon,
} from "lucide-react";

export const PERK_ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  wifi: Wifi,
  utensils: Utensils,
  "map-pin": MapPin,
  phone: Phone,
  "bed-double": BedDouble,
  coffee: Coffee,
  bath: Bath,
  "door-open": DoorOpen,
  armchair: Armchair,
  sofa: Sofa,
  sun: Sun,
  key: Key,
  lamp: Lamp,
  lightbulb: Lightbulb,
  refrigerator: Refrigerator,
  "washing-machine": WashingMachine,
  "cooking-pot": CookingPot,
  wind: Wind,
  tv: Tv,
  bed: Bed,
  warehouse: Warehouse,
  building: Building,
  "building-2": Building2,
  truck: Truck,
  car: Car,
  bus: Bus,
  bike: Bike,
  route: Route,
  shield: Shield,
  "shield-check": ShieldCheck,
  star: Star,
  award: Award,
  sparkles: Sparkles,
  heart: Heart,
  users: Users,
  "check-circle-2": CheckCircle2,
};
