import {
  Shield,
  ShieldCheck,
  BadgeCheck,
  CheckCircle2,
  Award,
  Medal,
  Trophy,
  Star,
  CircleStar,
  Crown,
  Sparkles,
  Zap,
  Flame,
  Target,
  Goal,
  Users,
  UserCheck,
  UsersRound,
  Handshake,
  HeartHandshake,
  HandHelping,
  ThumbsUp,
  HardHat,
  Briefcase,
  PersonStanding,
  TrendingUp,
  Activity,
  Rocket,
  Timer,
  CircleGauge,
  Truck,
  Car,
  Route,
  Navigation,
  Compass,
  Globe,
  MapPin,
  Flag,
  Milestone,
  Wrench,
  Fuel,
  Waypoints,
  TrafficCone,
  Plane,
  Ship,
  type LucideIcon,
} from "lucide-react";

export const TRUST_ICON_MAP: Record<string, LucideIcon> = {
  shield: Shield,
  "shield-check": ShieldCheck,
  "badge-check": BadgeCheck,
  "check-circle-2": CheckCircle2,
  award: Award,
  medal: Medal,
  trophy: Trophy,
  star: Star,
  "circle-star": CircleStar,
  crown: Crown,
  sparkles: Sparkles,
  zap: Zap,
  flame: Flame,
  target: Target,
  goal: Goal,
  users: Users,
  "user-check": UserCheck,
  "users-round": UsersRound,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "hand-helping": HandHelping,
  "thumbs-up": ThumbsUp,
  "hard-hat": HardHat,
  briefcase: Briefcase,
  "person-standing": PersonStanding,
  "trending-up": TrendingUp,
  activity: Activity,
  rocket: Rocket,
  timer: Timer,
  "circle-gauge": CircleGauge,
  truck: Truck,
  car: Car,
  route: Route,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  "map-pin": MapPin,
  flag: Flag,
  milestone: Milestone,
  wrench: Wrench,
  fuel: Fuel,
  waypoints: Waypoints,
  "traffic-cone": TrafficCone,
  plane: Plane,
  ship: Ship,
};
